name: YUAN Ye
description: Personal website
menu:
 - page: About me
   url: /about
 - page: Research
   url: /papers
   links:
    - title: Working papers
      url: "#working-papers"
    - title: Published papers
      url: "#published-papers"
 - page: Curriculum Vitae
   url: "https://yuanye-econ.github.io/research/CV-YuanYe-20220510.pdf"
 - page: Teaching
   url: /teaching
 menu_external:
 - title: My PKU Scholar Page
   url: "http://scholar.pku.edu.cn/yuanye-econ/"
 - title: My Research Gate Page
   url: "https://www.researchgate.net/profile/Ye-Yuan-139"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: yuanye-econ.github.io
locale: en_GB
