name: YUAN Ye 
description: Personal website
menu:
 - page: About me
   url: /about
 - page: Research 
   url: /papers
 - page: Curriculum Vitae
   url: "https://yuanye-econ.github.io/research/CV-YuanYe.pdf"
 - page: Teaching
   url: /teaching
menu_external:
 - title: My University Page
   url: "https://econ.pku.edu.cn/szdw/zzjs/ybjs/sjjxx/327511.htm"
 - title: My Research Gate
   url: "https://www.researchgate.net/profile/Ye-Yuan-139"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: 
locale: en_GB
